#!/usr/bin/env bash
set -e

INSTALL_PREFIX="${HOME}/.local"
TEMP_BUILD_DIR=/tmp/neovim
VERSION=1.22.1
ARCH=amd64
FILE="go${VERSION}.linux-${ARCH}.tar.gz"
URL="https://dl.google.com/go/${FILE}"

curl -O "${URL}"
rm -rf "${HOME}/.local/share/go"
mkdir -p "${HOME}/.local/share/"
tar -C "${HOME}/.local/share" -xzf "${FILE}"
ln -s "${HOME}/.local/share/go/bin/go" "${HOME}/.local/bin/go"
echo "Installed go version ${VERSION}"

