#!/usr/bin/env bash
set -e
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor >microsoft.gpg
sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
sudo apt install apt-transport-https
sudo apt update
sudo apt install -y code
rm microsoft.gpg

EXTENSIONS=(
    bmewburn.vscode-intelephense-client
    bradlc.vscode-tailwindcss
    chaitanyashahare.lazygit
    codeium.codeium
    continue.continue
    davidanson.vscode-markdownlint
    dioxuslabs.dioxus
    dssiqueira.drupal-8-snippets
    eamodio.gitlens
    ecmel.vscode-html-css
    esbenp.prettier-vscode
    fill-labs.dependi
    foxundermoon.shell-format
    golang.go
    james-yu.latex-workshop
    kevinrose.vsc-python-indent
    lihui.vs-color-picker
    marcostazi.vs-code-drupal
    mblode.twig-language-2
    mechatroner.rainbow-csv
    ms-azuretools.vscode-docker
    ms-kubernetes-tools.vscode-kubernetes-tools
    ms-python.black-formatter
    ms-python.debugpy
    ms-python.isort
    ms-python.python
    ms-python.vscode-pylance
    ms-toolsai.jupyter
    ms-toolsai.jupyter-keymap
    ms-toolsai.jupyter-renderers
    ms-toolsai.vscode-jupyter-cell-tags
    ms-toolsai.vscode-jupyter-slideshow
    ms-vscode-remote.remote-containers
    ms-vscode-remote.remote-ssh
    ms-vscode-remote.remote-ssh-edit
    ms-vscode.cmake-tools
    ms-vscode.cpptools
    ms-vscode.cpptools-extension-pack
    ms-vscode.cpptools-themes
    ms-vscode.remote-explorer
    mtxr.sqltools
    mtxr.sqltools-driver-mysql
    mtxr.sqltools-driver-pg
    naumovs.color-highlight
    pranaygp.vscode-css-peek
    redhat.vscode-yaml
    ritwickdey.liveserver
    rust-lang.rust-analyzer
    stanislav.vscode-drupal
    streetsidesoftware.code-spell-checker
    streetsidesoftware.code-spell-checker-french
    streetsidesoftware.code-spell-checker-german
    streetsidesoftware.code-spell-checker-portuguese
    streetsidesoftware.code-spell-checker-spanish
    sumneko.lua
    tamasfe.even-better-toml
    techtheawesome.rust-yew
    tekumara.typos-vscode
    timonwong.shellcheck
    twxs.cmake
    tyriar.lorem-ipsum
    usernamehw.errorlens
    vadimcn.vscode-lldb
    vscodevim.vim
    whatwedo.twig
    xdebug.php-debug
    zignd.html-css-class-completion
)
for ext in "${EXTENSIONS[@]}"; do
    code --install-extension "${ext}"
done
