#!/usr/bin/env bash
set -e

INSTALL_PREFIX="${HOME}/.local"
TEMP_BUILD_DIR=/tmp/neovim

rm -rf "${TEMP_BUILD_DIR}"
git clone https://github.com/neovim/neovim.git "${TEMP_BUILD_DIR}"
cd "${TEMP_BUILD_DIR}"
git checkout stable
make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX}"
make install
cd - >/dev/null
rm -rf "${TEMP_BUILD_DIR}"
echo "Successfully installed neovim under ${INSTALL_PREFIX}"
