#!/usr/bin/env bash
set -e

INSTALL_PREFIX="${HOME}/.local"
TEMP_BUILD_DIR=/tmp/neovim
VERSION=1.22.1
ARCH=amd64
FILE="go${VERSION}.linux-${ARCH}.tar.gz"
URL="https://go.dev/dl/${FILE}"

rm -rf "${HOME}/.local/share/go"
unlink "${HOME}/.local/bin/go" || echo "Skipping unlink"
curl -LO "${URL}"
mkdir -p "${HOME}/.local/share/"
tar -C "${HOME}/.local/share" -xzf "${FILE}"
mkdir -p "${HOME}/.local/bin/go"
ln -s "${HOME}/.local/share/go/bin/go" "${HOME}/.local/bin/go"
rm "${FILE}"
echo "Installed go version ${VERSION}"

