#!/usr/bin/env bash
set -e
TEMP_BUILD_DIR=/tmp/alacritty
VERSION="v0.16.1"
GIT_URL="https://github.com/alacritty/alacritty.git"

sudo apt install -y \
    cmake \
    libfontconfig1-dev \
    libfreetype6-dev \
    libxcb-xfixes0-dev \
    libxkbcommon-dev python3\
    pkg-config \

rm -rf "${TEMP_BUILD_DIR}"
git clone "${GIT_URL}" "${TEMP_BUILD_DIR}"
cd "${TEMP_BUILD_DIR}"
git checkout "${VERSION}"
cargo build --release

sudo cp target/release/alacritty /usr/local/bin
sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
sudo desktop-file-install extra/linux/Alacritty.desktop
sudo update-desktop-database
infocmp alacritty || sudo tic -xe alacritty,alacritty-direct extra/alacritty.info

cd - >/dev/null
rm -rf "${TEMP_BUILD_DIR}"

echo "Installed alacritty"
