#!/usr/bin/env bash
set -e
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
sudo apt install apt-transport-https
sudo apt update
sudo apt install -y code

EXTENSIONS=(
    eamodio.gitlens
    foxundermoon.shell-format
    golang.go
    james-yu.latex-workshop
    kevinrose.vsc-python-indent
    ms-azuretools.vscode-docker
    ms-kubernetes-tools.vscode-kubernetes-tools
    ms-python.debugpy
    ms-python.isort
    ms-python.python
    ms-python.vscode-pylance
    ms-toolsai.jupyter
    ms-toolsai.jupyter-keymap
    ms-toolsai.jupyter-renderers
    ms-toolsai.vscode-jupyter-cell-tags
    ms-toolsai.vscode-jupyter-slideshow
    ms-vscode-remote.remote-containers
    ms-vscode.cmake-tools
    ms-vscode.cpptools
    ms-vscode.cpptools-extension-pack
    ms-vscode.cpptools-themes
    mtxr.sqltools
    redhat.vscode-yaml
    rust-lang.rust-analyzer
    streetsidesoftware.code-spell-checker
    tamasfe.even-better-toml
    twxs.cmake
    usernamehw.errorlens
)
for ext in ${EXTENSIONS[@]}; do
    code --install-extension "${ext}"
done
