#!/usr/bin/env bash
set -e

sudo apt-get install -y software-properties-common \
    python-dev \
    python-pip \
    python3-dev \
    python3-pip
sudo add-apt-repository -y ppa:neovim-ppa/stable
sudo apt update
sudo apt-get install -y neovim
