#!/usr/bin/env bash
set -e
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
GIT_ROOT=$(
  cd "${SCRIPT_DIR}"
  git rev-parse --show-toplevel
  cd - >/dev/null 2>&1
)
CONFIG_TO_LINK=(
  Code/User
  nvim
)

# Prefixing every visible file/dir by "." and linking into $HOME
for file in $(realpath $GIT_ROOT/* | grep -v "/\.git\|/.*\.md\|/config"); do
  name="$(basename "${file}")"
  dotname=".${name}"

  [ -e "${HOME}/${dotname}" ] && continue
  git --git-dir "${file}/.git" rev-parse --git-dir &>/dev/null && continue

  ln -sfnv ${file#$HOME/} "${HOME}/${dotname}"
done

# Linking .config utils
for dotconfig in "${CONFIG_TO_LINK[@]}"; do
  abs_dst_path="${HOME}/.config/${dotconfig}"
  rm -rf "${abs_dst_path}"
  mkdir -p $(dirname "${abs_dst_path}")
  ln -sfnv "${GIT_ROOT}/config/${dotconfig}" "${abs_dst_path}"
done
